#!/bin/sh
REPO=https://github.com/cesar2535/cesar2535.github.io
upstream=origin

# git fetch $upstream
# if [ `git rev-list HEAD...$upstream/master --count` -ne 0 ]; then
#   echo "not deploying"
#   exit 1
# fi

npm i
rm -fr _public

git clone $REPO -b master _public

REV=`git describe --always`
gulp publish

cd _public
git add -A .
git commit -m "regen for $REV"
git push origin master
cd ..
